version: '3.8'

services:
  app:
    image: ghcr.io/lyttle-development/lyttle-cluster-manager:main
    privileged: true
    pid: host
    volumes:
      - /:/host
    ports:
      - 1111:3000
    deploy:
      mode: global
    environment:
      - NODE_ENV=production