version: '3.8'

services:
  app:
    image: ghcr.io/lyttle-development/lyttle-cluster-manager:main
    volumes:
      - /:/host
    deploy:
      mode: global
    environment:
      - NODE_ENV=production
      - API_TOKEN=your_api_token_here
    networks:
      - host_network

networks:
  host_network:
    external:
      name: "host"