version: '3.8'

services:
  app:
    image: ghcr.io/lyttle-development/lyttle-cluster-manager:main
    volumes:
      - /:/host
    deploy:
      mode: global
    environment:
      - ALLOWED_CLUSTER_HOSTS=value-here
      - ALLOWED_USERS=value-here
      - API_TOKEN=value-here
      - GOOGLE_CLIENT_ID=value-here
      - GOOGLE_CLIENT_SECRET=value-here
      - NEXTAUTH_SECRET=value-here
      - NEXTAUTH_URL=value-here
    networks:
      - host_network

networks:
  host_network:
    external:
      name: "host"